### ISSUE TITLE
API limit - github login instructions

### ISSUE THREAD

**Issue by tylermcinnes** [GenomicsAotearoa/AGM-workshop-2023#1]

**Comment by jguhlin** [comment]
Assuming this is what I'm getting as well. Can we download the repo locally?

```bash
(nf-core) bash-4.2$ export NXF_SINGULARITY_CACHEDIR=/nesi/nobackup/nesi02659/nextflow-workshop
(nf-core) bash-4.2$ echo $NXF_SINGULARITY_CACHEDIR
/nesi/nobackup/nesi02659/nextflow-workshop
(nf-core) bash-4.2$ nextflow run nextflow-io/hello
N E X T F L O W  ~  version 23.04.0
Pulling nextflow-io/hello ...
WARN: Cannot read project manifest -- Cause: API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
API rate limit exceeded -- Provide your GitHub user name and password to get a higher rate limit
(nf-core) bash-4.2$ 
```

**Comment by jguhlin** [comment]
This means nothing in session 1 is working, should we clone the repo's locally and drop the revision stuff?

@tylermcinnes @DininduSenanayake

**Comment by DininduSenanayake** [comment]
@jguhlin Yep. I will populate it for everyone ( this is what we had to do for October workshops as well). I am at a meeting till 11.30. Will take care of it after that.

**Comment by DininduSenanayake** [comment]
@jguhlin If you are testing the material now, can you copy the assets to you home with `cp -r /nesi/project/nesi02659/nextflow-workshop/assets/* ~/.nextflow/assets`
I will copy it to other later

**Comment by jguhlin** [comment]
I went through and ran everything a few times, all seems to be working.
