### ISSUE TITLE
Parameter Files

### ISSUE THREAD

**Issue by jguhlin** [GenomicsAotearoa/AGM-workshop-2023#2]
![image](https://github.com/GenomicsAotearoa/AGM-workshop-2023/assets/1838344/f2cc0e07-3f6f-4ee2-97b7-b91c772912f8)

Seems ** Parameter Files is meant to be a header or a note...

**Comment by DininduSenanayake** [comment]
Thanks @jguhlin I will start fixing the syntax  now

**Comment by DininduSenanayake** [comment]
Fixed in 5a64842
